tap "homebrew/services"
tap "minio/stable"
# All in one for **env
brew "anyenv"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Command-line interface for SQLite
brew "sqlite"
# Official Amazon AWS command-line interface
brew "awscli"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Simple, fast and user-friendly alternative to find
brew "fd"
# OpenType text shaping engine
brew "harfbuzz"
# TIFF library and utilities
brew "libtiff"
# New file format for still image compression
brew "jpeg-xl"
# Play, record, convert, and stream many audio and video codecs
brew "ffmpeg-full", link: true
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Database migrations CLI tool
brew "golang-migrate"
# Image manipulation
brew "netpbm"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# Tools and libraries to manipulate images in many formats
brew "imagemagick-full", link: true
# Lightweight and flexible command-line JSON processor
brew "jq"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Node.js version manager
brew "nodebrew"
# Development kit for the Java programming language
brew "openjdk@17"
# Simplistic interactive filtering tool
brew "peco"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql@16", restart_service: :changed
# SVG rendering tool and library
brew "resvg"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Securely stores and accesses AWS credentials in a development environment
cask "aws-vault-binary"
cask "font-symbols-only-nerd-font"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
vscode "1yib.rust-bundle"
vscode "4ops.terraform"
vscode "abusaidm.html-snippets"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "anthropic.claude-code"
vscode "christian-kohler.path-intellisense"
vscode "docker.docker"
vscode "dsznajder.es7-react-js-snippets"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "fill-labs.dependi"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "juanblanco.solidity"
vscode "lorenzopirro.rust-flash-snippets"
vscode "mosapride.zenkaku"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "msjsdiag.vscode-react-native"
vscode "ritwickdey.liveserver"
vscode "run-at-scale.terraform-doc-snippets"
vscode "rust-lang.rust-analyzer"
vscode "sidthesloth.html5-boilerplate"
vscode "streetsidesoftware.code-spell-checker"
vscode "styled-components.vscode-styled-components"
vscode "swellaby.rust-pack"
vscode "tamasfe.even-better-toml"
vscode "vscodevim.vim"
vscode "xabikos.javascriptsnippets"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/haya14busa/goplay/cmd/goplay"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/josharian/impl"
go "honnef.co/go/tools/cmd/staticcheck"
npm "@anthropic-ai/claude-code"
npm "@google/gemini-cli"
npm "@notionhq/notion-mcp-server"
npm "@openai/codex"
npm "corepack"
npm "wrangler"
